In [2]:
import sys
import numpy as np

## Basic Numpy Arrays

In [21]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [22]:
a = np.array([1, 2, 3, 4])

In [23]:
b = np.array([0, .5, 1, 1.5, 2])

In [24]:
a[0], a[1]

(1, 2)

In [25]:
a[0:]

array([1, 2, 3, 4])

In [26]:
a[1:3]

array([2, 3])

In [27]:
a[1:-1]

array([2, 3])

In [28]:
a[::2]

array([1, 3])

In [29]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [30]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [31]:
b[[0, 2, -1]]

array([0., 1., 2.])

In [32]:
b = np.array([0, ])

## Array Types

In [33]:
a

array([1, 2, 3, 4])

In [34]:
a.dtype

dtype('int32')

In [35]:
b

array([0])

In [36]:
b.dtype

dtype('int32')

In [37]:
np.array([1, 2, 3, 4], dtype=np.float)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_3804\217965920.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1, 2, 3, 4], dtype=np.float)


array([1., 2., 3., 4.])

In [38]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [39]:
c = np.array(['a', 'b', 'c'])

In [40]:
c.dtype

dtype('<U1')

In [3]:
d = np.array([{'a': 1}, sys])

In [4]:
d.dtype

dtype('O')

## Dimensions and shapes


In [5]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [6]:
A.shape

(2, 3)

In [45]:
A.ndim

2

In [46]:
A.size

6

In [47]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [48]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [49]:
B.shape

(2, 2, 3)

In [50]:
B.ndim

3

In [51]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [52]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

C:\Users\Administrator\AppData\Local\Temp\ipykernel_3804\548599459.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [53]:
C.dtype

dtype('O')

In [54]:
C.shape

(2,)

In [55]:
C.size

2

In [56]:
type(C[0])

list

## Indexing and Slicing of Matrices

In [57]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [58]:
A[1]

array([4, 5, 6])

In [59]:
A[1][0]

4

In [60]:
# A[d1, d2, d3, d4]

In [61]:
A[1, 0]

4

In [62]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [64]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [65]:
A[:2, 2:]

array([[3],
       [6]])

In [66]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
A[1] = np.array([10, 10, 10])

In [68]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [69]:
A[2] = 99

In [70]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

## Summary statistics

In [71]:
a = np.array([1, 2, 3, 4])

In [72]:
a.sum()

10

In [73]:
a.mean()

2.5

In [74]:
a.std()

1.118033988749895

In [75]:
a.var()

1.25

In [76]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [77]:
A.sum()

45

In [78]:
A.mean()

5.0

In [79]:
A.std()

2.581988897471611

In [80]:
A.sum(axis=0)

array([12, 15, 18])

In [81]:
A.sum(axis=1)

array([ 6, 15, 24])

In [82]:
A.mean(axis=0)

array([4., 5., 6.])

In [83]:
A.mean(axis=1)

array([2., 5., 8.])

In [84]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [85]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...

## Broadcasting and Vectorized operations

In [86]:
a = np.arange(4)

In [87]:
a

array([0, 1, 2, 3])

In [88]:
a + 10

array([10, 11, 12, 13])

In [89]:
a * 10

array([ 0, 10, 20, 30])

In [90]:
a

array([0, 1, 2, 3])

In [91]:
a += 100

In [92]:
a

array([100, 101, 102, 103])

In [93]:
l = [0, 1, 2, 3]

In [94]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [95]:
a = np.arange(4)

In [96]:
a

array([0, 1, 2, 3])

In [97]:
b = np.array([10, 10, 10, 10])

In [98]:
b

array([10, 10, 10, 10])

In [99]:
a + b

array([10, 11, 12, 13])

In [100]:
a * b

array([ 0, 10, 20, 30])

## Boolean arrays
_(Also called masks)_

In [101]:
a = np.arange(4)

In [102]:
a

array([0, 1, 2, 3])

In [103]:
a[0], a[-1]

(0, 3)

In [104]:
a[[0, -1]]

array([0, 3])

In [105]:
a[[True, False, False, True]]

array([0, 3])

In [106]:
a

array([0, 1, 2, 3])

In [107]:
a >= 2

array([False, False,  True,  True])

In [108]:
a[a >= 2]

array([2, 3])

In [109]:
a.mean()

1.5

In [110]:
a[a > a.mean()]

array([2, 3])

In [111]:
a[~(a > a.mean())] # ~ is the not operator

array([0, 1])

In [112]:
a[(a == 0) | (a == 1)] # | is the or operator

array([0, 1])

In [113]:
a[(a <= 2) & (a % 2 == 0)] # & is the and operator

array([0, 2])

In [114]:
A = np.random.randint(100, size=(3, 3))

In [115]:
A

array([[31, 86, 19],
       [94, 28, 85],
       [ 7, 59, 98]])

In [116]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([31, 19, 28,  7, 98])

In [117]:
A > 30

array([[ True,  True, False],
       [ True, False,  True],
       [False,  True,  True]])

In [118]:
A[A > 30]

array([31, 86, 94, 85, 59, 98])

## Linear Algebra

In [119]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [120]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [121]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [122]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [123]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [124]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

## Size of objects in Memory

In [126]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [127]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [128]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [129]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [130]:
np.dtype(float).itemsize

8

### Lists are even larger

In [131]:
# A one-element list
sys.getsizeof([1])

64

In [132]:
# An array of one element in numpy
np.array([1]).nbytes

4

### And performance is also important

In [133]:
l = list(range(100000))

In [134]:
a = np.arange(100000)

In [135]:
%time np.sum(a ** 2)

CPU times: total: 0 ns
Wall time: 1e+03 µs


216474736

In [136]:
%time sum([x ** 2 for x in l])

CPU times: total: 15.6 ms
Wall time: 19 ms


333328333350000

## Useful Numpy functions

### `random` 

In [137]:
np.random.random(size=2)

array([0.20801694, 0.38372949])

In [138]:
np.random.normal(size=2)

array([1.39846864, 0.80694495])

In [139]:
np.random.rand(2, 4)

array([[0.63687278, 0.65039981, 0.14733005, 0.40468661],
       [0.19909759, 0.99413864, 0.02455059, 0.48972084]])

### `arange`

In [140]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [142]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### `reshape`

In [143]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [144]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

###  `linspace`

In [145]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [146]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [147]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

### `zeros`, `ones`, `empty`

In [148]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [149]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [150]:
np.zeros((3, 3), dtype=np.int)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_3804\383259716.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros((3, 3), dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [151]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [152]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [153]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [154]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

---
### `identity` and `eye`

In [155]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [156]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [157]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [158]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [159]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])