In [2]:
import numpy as np

In [4]:
print(np.__version__)

1.22.4


In [6]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [7]:
a.shape

(3,)

In [8]:
a.dtype

dtype('int32')

In [9]:
a.ndim

1

In [10]:
a.size

3

In [11]:
a.itemsize

4

In [12]:
a[0]

1

In [14]:
a[0] = 10
a

array([10,  2,  3])

In [15]:
b = a * np.array([2, 0, 2])
b

array([20,  0,  6])

#### Difference between np.array and py list

In [18]:
l = [1, 2, 3]
a = np.array(1, 2, 3)


TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [17]:
l, a

([1, 2, 3], array([10,  2,  3]))

In [20]:
l.append(4)
l

[1, 2, 3, 4, 4]

In [21]:
a.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [24]:
l = [1, 2, 3]
l = l + [4]
l

[1, 2, 3, 4]

In [27]:
a = a + np.array([4]) # broadcasting
a

array([22, 14, 15])

In [28]:
l = [1, 2, 3]
l = l * 2
l

[1, 2, 3, 1, 2, 3]

In [32]:
a = np.array([1, 2, 3])
a = a * 2
a

array([2, 4, 6])

In [34]:
a = np.array([1, 2, 3])
np.sqrt(a)


array([1.        , 1.41421356, 1.73205081])

 Dot product of two vectors

In [35]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]
dot = 0
for i in range(len(l1)):
    dot += l1[i] * l2[i]
dot

32

In [36]:
a1 = np.array(l1)
a2 = np.array(l2)
dot = np.dot(a1, a2)
dot

32

In [38]:
sum1 = a1 * a2
dot = np.sum(sum1)
dot

32

In [39]:
dot = (a1 * a2).sum()
dot

32

In [40]:
dot =  a1 @ a2
dot

32

#### Multidimensional (nd) arrays

In [41]:
a = np.array([[1, 2, 3],
            [4, 5, 6]])
a.shape

(2, 3)

In [42]:
a[0]

array([1, 2, 3])

In [43]:
a[0, 0]

1

In [45]:
a[:, 0]

array([1, 4])

In [46]:
a[0, :]

array([1, 2, 3])

In [47]:
a.T # transposing

array([[1, 4],
       [2, 5],
       [3, 6]])

In [49]:
a = np.array([[1, 2],
            [3, 4]])
np.linalg.inv(a) #Matrix inverse calculation

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [50]:
np.linalg.det(a) #Matrix determinant calculation

-2.0000000000000004

In [52]:
np.diag(a) #Diagonal elements

array([1, 4])

#### Indexing and slicing

In [59]:
a = np.array([[1, 2, 3, 4],
            [5, 6, 7, 8]])

In [60]:
a[0, 1]

2

In [61]:
a[0,:]

array([1, 2, 3, 4])

In [62]:
a[:, 0]

array([1, 5])

In [63]:
a[-1, -1]

8

#### Boolean indexing

In [66]:
a = np.array([[1,2],
            [3, 4],
            [5, 6]])

In [67]:
boll_idx = (a > 2)
boll_idx

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [68]:
a[a > 2] #1D array

array([3, 4, 5, 6])

In [70]:
b = np.where(a > 2, a, -1) # if a > 2, a, else -1; same shape
b

array([[-1, -1],
       [ 3,  4],
       [ 5,  6]])

In [73]:
a = np.array([10, 19, 30, 41, 50, 61]) #fancy indexing
b = [1, 3, 5]
a[b]


array([19, 41, 61])

In [74]:
even = np.argwhere(a % 2 == 0).flatten()
a[even]

array([10, 30, 50])

#### Reshaping arrays

In [76]:
a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

In [79]:
b = a.reshape(2, 3)
b, b.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [82]:
b = a[np.newaxis, :]
b, b.shape

(array([[1, 2, 3, 4, 5, 6]]), (1, 6))

In [81]:
b = a[:, np.newaxis]
b, b.shape

(array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]]),
 (6, 1))

#### Concatenating

In [84]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6]])

In [86]:
c = np.concatenate((a, b), axis=0) # axis=0: row-wise
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [88]:
c = np.concatenate((a, b), axis=None) # axis=None: flatten
c

array([1, 2, 3, 4, 5, 6])

In [90]:
c = np.concatenate((a, b.T), axis=1) # axis=1: column-wise
c

array([[1, 2, 5],
       [3, 4, 6]])

In [92]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [93]:
c = np.hstack((a, b))
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [95]:
c = np.vstack((a, b))
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### Functions and Axis

In [96]:
a = np.array([[7, 8, 9, 10, 11, 12, 13], [17, 18, 19, 20, 21, 22, 23]])
a

array([[ 7,  8,  9, 10, 11, 12, 13],
       [17, 18, 19, 20, 21, 22, 23]])

In [99]:
a.sum(), a.sum(axis=0), a.sum(axis=1)

(210, array([24, 26, 28, 30, 32, 34, 36]), array([ 70, 140]))

In [100]:
a.mean(), a.mean(axis=0), a.mean(axis=1)

(15.0, array([12., 13., 14., 15., 16., 17., 18.]), array([10., 20.]))

#### Copying arrays

In [101]:
a = np.array([1, 2, 3])
b = a # shallow copy
b[0] = 42
a


array([42,  2,  3])

In [102]:
a = np.array([1, 2, 3])
b = a.copy() # deep copy
b[0] = 42
a

array([1, 2, 3])

#### Generating arrays

In [103]:
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [105]:
a = np.ones((2, 3), dtype=np.int64)
a

array([[1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [106]:
a = np.full((2, 3), 42)
a

array([[42, 42, 42],
       [42, 42, 42]])

In [107]:
#identity matrix
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [109]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [111]:
#linspace (start, stop, num)
a = np.linspace(0, 1, 5)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### Random numbers

In [113]:
a = np.random.random((3, 2)) #uniform distribution;
a

array([[0.61436328, 0.13065394],
       [0.02245532, 0.28802418],
       [0.66069099, 0.38582739]])

In [120]:
a = np.random.randn(3, 2) # normal/gaussian distribution mean=0, var=1
a

array([[0.88538413, 1.60416611],
       [1.83981129, 1.88517886],
       [1.36681807, 1.01655113]])

In [159]:
a = np.random.randn(1000)
a.mean(), a.var()


(-0.02756069217050719, 1.0482756278860619)

In [158]:
a = np.random.random((1000))
a.mean(), a.var()

(0.49607213451625803, 0.08334450915877456)

In [161]:
a = np.random.randint(3, 10, (3, 3)) #start, stop, shape
a

array([[8, 4, 6],
       [7, 4, 3],
       [5, 7, 8]])

In [163]:
a = np.random.choice(5, size=10)
a

array([2, 2, 1, 1, 3, 2, 3, 4, 3, 0])

In [167]:
a = np.random.choice([-7, -8, -9], size=10)
a

array([-8, -7, -8, -7, -7, -8, -8, -8, -8, -9])

In [3]:
a = np.array([6, -2])
b = np.array([-4, 4])
a + b

array([2, 2])